USE [Hera]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[link_geo_maps](
	[territorio] [nvarchar](50) NOT NULL,
	[lat] [float] NOT NULL,
	[long] [float] NOT NULL,
	[link] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_link_geo_maps] PRIMARY KEY CLUSTERED 
(
	[territorio] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
